### ISSUE TITLE
Attempting to roll a skill or weapon without a bonus spams the chat.

### ISSUE THREAD

**Issue by Vandaag12** [kevinsearle/roll20-character-sheets#1]
Using the Stars Without Number character sheet available on Roll20, whenever you attempt to roll a skill or use a weapon, your chat will be spammed with the following line:  No attribute was found for @{CHARACTER NAME|ATTRIBUTEBonus}, varying depending on what your set character name and attribute bonus for the skill is.

Attached is an image of the error in question which spams your chat whenever you click the macro, as well as a picture of the attributes in question.
![u79xafu](https://cloud.githubusercontent.com/assets/27614490/25069913/89958e36-225c-11e7-8b7d-57c8be62c7f6.png)
![t5ouzhu](https://cloud.githubusercontent.com/assets/27614490/25069924/d83d85fc-225c-11e7-9e6c-c6157d096ec3.png)

**Comment by kevinsearle** [comment]
Thanks for reporting this. This fix has been ready for over a week now _but_ is awaiting Roll20 to merge into their code see the [pull request](https://github.com/Roll20/roll20-character-sheets/pull/2519).

**Comment by kevinsearle** [comment]
Specifically, this issue: https://github.com/Roll20/roll20-character-sheets/issues/2525
